// Generated by gencpp from file ros2_is_fun/my_message.msg
// DO NOT EDIT!


#ifndef ROS2_IS_FUN_MESSAGE_MY_MESSAGE_H
#define ROS2_IS_FUN_MESSAGE_MY_MESSAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros2_is_fun
{
template <class ContainerAllocator>
struct my_message_
{
  typedef my_message_<ContainerAllocator> Type;

  my_message_()
    : message()  {
    }
  my_message_(const ContainerAllocator& _alloc)
    : message(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::ros2_is_fun::my_message_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros2_is_fun::my_message_<ContainerAllocator> const> ConstPtr;

}; // struct my_message_

typedef ::ros2_is_fun::my_message_<std::allocator<void> > my_message;

typedef boost::shared_ptr< ::ros2_is_fun::my_message > my_messagePtr;
typedef boost::shared_ptr< ::ros2_is_fun::my_message const> my_messageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros2_is_fun::my_message_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros2_is_fun::my_message_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros2_is_fun::my_message_<ContainerAllocator1> & lhs, const ::ros2_is_fun::my_message_<ContainerAllocator2> & rhs)
{
  return lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros2_is_fun::my_message_<ContainerAllocator1> & lhs, const ::ros2_is_fun::my_message_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros2_is_fun

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ros2_is_fun::my_message_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros2_is_fun::my_message_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros2_is_fun::my_message_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros2_is_fun::my_message_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros2_is_fun::my_message_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros2_is_fun::my_message_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros2_is_fun::my_message_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5f003d6bcc824cbd51361d66d8e4f76c";
  }

  static const char* value(const ::ros2_is_fun::my_message_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5f003d6bcc824cbdULL;
  static const uint64_t static_value2 = 0x51361d66d8e4f76cULL;
};

template<class ContainerAllocator>
struct DataType< ::ros2_is_fun::my_message_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros2_is_fun/my_message";
  }

  static const char* value(const ::ros2_is_fun::my_message_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros2_is_fun::my_message_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string message\n"
;
  }

  static const char* value(const ::ros2_is_fun::my_message_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros2_is_fun::my_message_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct my_message_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros2_is_fun::my_message_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros2_is_fun::my_message_<ContainerAllocator>& v)
  {
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS2_IS_FUN_MESSAGE_MY_MESSAGE_H
